- name: gcp_create_vm
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - files/gcp_vars

  tasks:
  - name: create a public ip
    gcp_compute_address:
      name: address-instance
      region: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: public_ip
      
  - name: create a VM
    gcp_compute_instance:
      state: present
      status: RUNNING
      name: "{{ vm_name }}"
      machine_type: n1-standard-1
      disks:
      - auto_delete: true
        boot: true
        initialize_params:
          source_image: "projects/windows-cloud/global/images/family/windows-2019"
      network_interfaces:
      - access_configs:
        - name: External NAT
          nat_ip: "{{ public_ip }}"
          type: ONE_TO_ONE_NAT
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
      - https://www.googleapis.com/auth/compute
      metadata:
        sysprep-specialize-script-ps1: "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/fvzwieten/ansible4windows/master/createuser.ps1'))"
    register: instance

  - name: remove metadata
    gcp_compute_instance:
      state: present
      status: RUNNING
      name: "{{ vm_name }}"
      metadata: {}

  - name: Wait for VM provisioning..
    wait_for:
      host: "{{ public_ip.address }}"
      port: 3389
      delay: 60
      timeout: 600

  - name: Wait for VM to be ready..
    wait_for:
      host: "{{ public_ip.address }}"
      port: 5986
      delay: 60
      timeout: 600
      
  - name: add the just created VM to the inventory
    add_host:
      name: '{{ public_ip.address }}'
      groups: new_vm

- name: set ansible password in a safe manner
  hosts: new_vm
  gather_facts: no
  vars_files:
  - files/winrm_vars
  vars:
  - pwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63323162323330383933663232333562356432333638643430393139363438643331366466346266
          3836623561336234393461366335376535663466393365360a623031393130343935313930336464
          37326332353863306666363131373565363163376637386561376562643661356361363964396130
          3065336435343966660a366665343663623638636565353265326430363764393238663636316162
          3034
 
  tasks:
  - name: Show password
    debug:
      var: pwd
      
  - name: set definitive ansible password
    win_user:
      name: ansible
      password: "{{ pwd }}"
      state: present
