- name: test gcp_compute_windows_pwd
  hosts: localhost
  connection: local
  vars_files:
  - files/gcp_vars

  tasks:
  - name: run the new module
    gcp_compute_win_password:
      instance: "{{ vm_name }}"
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      email: "{{ gcp_email }}"
      credential_file: "{{ gcp_cred_file }}"
      #credential_file: "files/ansible-workshop-244208-be238b493af9.json"
    username: "ansible"
    register: testout

  - name: dump test output
    debug:
      msg: "{{ testout }}"
