- name: gcp_create_vm
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    files/gcp_vars

  tasks:
   - name: create a public ip
     gcp_compute_address:
       name: address-instance
       region: "{{ gcp_region }}"
       project: "{{ gcp_project }}"
       auth_kind: "{{ gcp_cred_kind }}"
       service_account_file: "{{ gcp_cred_file }}"
       state: present
     register: public_ip
      
   - name: create a VM
     gcp_compute_instance:
         state: present
         status: RUNNING
         name: "{{ vm_name }}"
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             initialize_params:
               source_image: "projects/windows-cloud/windows-server-2019-dc-v20200114"
         network_interfaces:
              - access_configs:
                  - name: External NAT
                    nat_ip: "{{ public_ip }}"
                    type: ONE_TO_ONE_NAT
         zone: "{{ gcp_zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance
       
#   - name: Wait for SSH to come up
#     wait_for: host={{ public_ip.address }} port=22 delay=10 timeout=60
