- name: gcp_create_vm
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - files/gcp_vars

  tasks:
  - name: create a public ip
    gcp_compute_address:
      name: address-instance
      region: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
    register: public_ip
      
  - name: create a VM
    gcp_compute_instance:
      state: present
      status: RUNNING
      name: "{{ vm_name }}"
      machine_type: n1-standard-1
      disks:
      - auto_delete: true
        boot: true
        initialize_params:
          source_image: "projects/windows-cloud/global/images/family/windows-2019"
      network_interfaces:
      - access_configs:
        - name: External NAT
          nat_ip: "{{ public_ip }}"
          type: ONE_TO_ONE_NAT
      zone: "{{ gcp_zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
      - https://www.googleapis.com/auth/compute
      metadata:
        sysprep-specialize-script-ps1: "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/fvzwieten/ansible4windows/master/createuser.ps1'))"
    register: instance

  - name: Wait for VM provisioning..
    wait_for:
      host: "{{ public_ip.address }}"
      port: 3389
      delay: 60
      timeout: 600

  - name: Wait for VM to be ready..
    wait_for:
      host: "{{ public_ip.address }}"
      port: 5986
      delay: 60
      timeout: 600
      
  - name: add the just created VM to the inventory
    add_host:
      name: '{{ public_ip.address }}'
      groups: new_vm

- name: set ansible password in a safe manner
  hosts: new_vm
  gather_facts: no
  vars_files:
  - files/winrm_vars

  tasks:
  - name: set definitive ansible password
    win_user:
      name: ansible
      password: "P@ssw0rd"
      state: present
