- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars_files:
    files/gcp_vars

  tasks:
   - name: create a VM
     gcp_compute_instance:
         state: present
         name: test-vm
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             initialize_params:
               source_image: "projects/rhel-cloud/global/images/rhel-8-v20190618"
             #source: "{{ disk }}"
         network_interfaces:
              - access_configs:
                  - name: External NAT
#                    nat_ip: "{{ address }}"
                    type: ONE_TO_ONE_NAT
         zone: "{{ gcp_zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance

   - name: show result
     debug:
       msg: "{{ instance }}"
       
#   - name: Wait for SSH to come up
#     wait_for: host={{ instance.address }} port=22 delay=10 timeout=60
